New ZoomInFadeOut animation added
aagarwal1012/Animated-Text-Kit pull request #209
Opened 2021-03-12 14:36 UTC by saurabhraj042

Issues:
Fixes #207 

Description:
I added a new ZoomInFadeOut animation. 
Updated the Example app and readme.md accordingly

This is how the animation is looking right now
![zoomInFadeOut](https://user-images.githubusercontent.com/47533509/110954297-57f13980-836e-11eb-8352-8693dfce0cf4.gif)

2021-03-12 18:25 UTC, SirusCodes requested changes
Add a gif

2021-03-12 18:45 UTC, awhitford commented
> Add a gif

See #202 for details.  (We realize that we lack guidance on this; hence the issue.)

2021-03-12 19:10 UTC, awhitford requested changes
@aagarwal1012 @SirusCodes

Now that I am looking at this closer, it strikes me that this is really nothing more than the _Scale_ animation that simply short-circuits the _Scale Out_.  This reminds me of the adjustment made to the _Rotate_ animation that offers a flag (`rotateOut`) to short-circuit the _Rotate Out_.  I'm thinking a similar approach makes sense.  What do you think?

2021-03-12 19:42 UTC, awhitford commented on lib/src/zoom_in_fade_out.dart
> +class ZoomInFadeOutAnimatedTextKit extends AnimatedTextKit {
I now see that @aagarwal1012 did confirm that `Kit` classes are no longer required.  See #211.  As a result, I would drop this class.

(Obviously, there is still the grander question of:  "Is this sufficiently different than the existing _Scale_ animation?")

2021-03-13 03:42 UTC, saurabhraj042 commented on lib/src/zoom_in_fade_out.dart
> +class ZoomInFadeOutAnimatedTextKit extends AnimatedTextKit {
@awhitford Can you please guide me how should I do that , I'm completely clueless here  !

2021-03-13 05:54 UTC, SirusCodes commented
> @aagarwal1012 @SirusCodes
> 
> Now that I am looking at this closer, it strikes me that this is really nothing more than the _Scale_ animation that simply short-circuits the _Scale Out_. This reminds me of the adjustment made to the _Rotate_ animation that offers a flag (`rotateOut`) to short-circuit the _Rotate Out_. I'm thinking a similar approach makes sense. What do you think?

I feel it just scales in rather than out. So, we can add an enum `Scale.in` and `Scale.out` to see what animation user is expecting🤔

2021-03-13 09:06 UTC, aagarwal1012 commented
> Is this sufficiently different than the existing Scale animation?

Yes, this animation is somewhat an upscaled version of the Scale Animation. I would prefer rather than creating a separate `ZoomInFadeOut` animated text -- we should rather add some more customizable parameter to the Scale Animated Text so that it could mimic any animation possibility related to the zoom-in/zoom-out effects possible.

2021-03-13 09:10 UTC, saurabhraj042 commented
@aagarwal1012 at first I thought to do the same, but because of the mention to create a new effect I did this.So should I go ahead and make changes in the Scale animation itself

2021-03-13 09:11 UTC, aagarwal1012 commented
@saurabhraj042, before proceeding further, I just wanted to see what @awhitford @SirusCodes react to this idea. Let's wait for their response.

2021-03-13 09:46 UTC, awhitford commented
> I would prefer rather than creating a separate `ZoomInFadeOut` animated text -- we should rather add some more customizable parameter to the Scale Animated Text so that it could mimic any animation possibility related to the zoom-in/zoom-out effects possible.

I agree with this sentiment simply because of the similarity of the proposed `ZoomInFadeOut` with `Scale`, it seems more appropriate to tweak the `Scale` -- especially when it literally looks like some simple short-circuiting.

Note that the idea of tweaking an existing Animation to do _too much_ is also a risk.  However, in this case, it seems like the best approach.

I suggest submitting a fresh PR that enhances Scale to also offer Effect 15.

2021-03-13 09:48 UTC, saurabhraj042 commented
@awhitford @SirusCodes @aagarwal1012  if you all agree with this then please open an issue and assign it to me !

2021-03-13 10:06 UTC, awhitford commented
> if you all agree with this then please open an issue and assign it to me !

@saurabhraj042 You can still reference #207.  (The lineage of comments is a helpful record.)

2021-03-13 10:44 UTC, SirusCodes commented
> if you all agree with this then please open an issue and assign it to me !

I would like to plan this out in https://github.com/aagarwal1012/Animated-Text-Kit/discussions/212 and then we can continue with the progress

2021-03-14 04:47 UTC, saurabhraj042 commented
@aagarwal1012 @awhitford @SirusCodes So should I drop the changes made in this PR because as in the Version 3 we are planning to drop the kit class and that will require refactoring all other animation classes also so merging this PR will be of no good.

2021-03-14 08:13 UTC, aagarwal1012 commented
@saurabhraj042, I would suggest dropping this PR for now and let's start from a fresh piece of code.

2021-03-14 08:15 UTC, saurabhraj042 commented
@aagarwal1012  how about we change the legacy kit class first ? can you assign that issue to me

2021-03-21 10:43 UTC, aagarwal1012 commented
@saurabhraj042, #216 have been created by @awhitford that should be fine for now.

2021-03-25 15:14 UTC, aagarwal1012 commented
Closing this PR, rework required!

2021-03-25 15:14 UTC, closed without merging